Ajust readme, revisao Camila
cumbucadev/gitcaos pull request #80
Opened 2024-10-29 15:22 UTC by laistdomiciano

2024-10-29 16:58 UTC, camilamaia requested changes
Consegues atualizar o título e a descrição do PR para ficar mais claro? Valeu!

2024-10-29 16:58 UTC, camilamaia commented on README.md
> +Define um ambiente de respeito e inclusão, onde todos são tratados com empatia e profissionalismo. Comportamentos ofensivos, assédio ou falta de respeito são inaceitáveis e sujeitam-se a medidas corr
Acho que o meu comentário acabou se perdendo no outro PR:

"Aee, obrigada! Talvez seria legal adicionar uma introdução dizendo que é um documento para definir as diretrizes da comunidade. Algo como:

"O arquivo CODE_OF_CONDUCT.md estabelece as diretrizes de comportamento esperado para todos os participantes da nossa comunidade. Ele busca garantir um ambiente inclusivo, seguro e acolhedor, promovendo o respeito mútuo e a colaboração.

Essas diretrizes são essenciais para manter um espaço em que todos possam contribuir e aprender, independentemente de suas origens ou experiências. Esperamos que todos sigam essas normas e ajudem a fortalecer uma cultura de respeito e apoio dentro da comunidade."

O quê vc acha? Só sugestão mesmo, fica à vontade para adaptar como achar melhor"

2024-10-31 11:36 UTC, laistdomiciano commented
Oi Camila, acabei de alterar o texto de acordo com sua recomendação :) Obrigada!

2024-10-31 13:10 UTC, camilamaia commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@laistdomiciano Ooops, acho que aqui você adicionou de novo o arquivo sem querer. Na hora de dar o git add, é interessante não utilizar o `git add --all`, porque assim você adiciona tudo sem saber o quê tá indo de fato.

Eu sugiro sempre dar o `git status`. Ver todos os arquivos e adicionar um por um os que vc quer. Nesse exemplo seria: git add README.md

2024-10-31 13:24 UTC, laistdomiciano commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
🫣 Tem como reverter esse commit para não adicionar o arquivo de novo?

2024-10-31 14:42 UTC, camilamaia approved these changes
🌟🌟

2024-10-31 14:43 UTC, merged